name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the ORISO platform
title: "[Bug]: "
labels: ["bug", "triage"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: affected-service
    attributes:
      label: Affected Service/Component
      description: Which service(s) or component(s) are affected? (You can select multiple)
      multiple: true
      options:
        - Frontend (ORISO-Frontend)
        - Admin Panel (ORISO-Admin)
        - User Service
        - Tenant Service
        - Agency Service
        - Consulting Type Service
        - Keycloak (Auth)
        - Matrix/Element (Messaging)
        - Nginx (Gateway)
        - Infrastructure/Kubernetes
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug?
      options:
        - P0-Critical
        - P1-High
        - P2-Medium
        - P3-Low
      default: 2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121] (if applicable)
        - Java Version: [e.g., Java 11/17] (if applicable)
        - Node Version: [e.g., Node 18.16.1] (if applicable)
        - Environment: [Local/Dev/Staging/Production]
        - Service Version/Commit: [if known]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Error Messages
      description: Please copy and paste any relevant log output or error messages. This will be automatically formatted as code.
      placeholder: Paste logs or error messages here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem. You can drag and drop images here.
      placeholder: |
        ![Screenshot description](image-url)
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If you have found a temporary workaround, please describe it here.
      placeholder: Describe any workaround you've found...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all relevant information above
          required: true
        - label: I can reproduce this bug consistently
          required: true


