name: 📚 Documentation
description: Request documentation improvements or report documentation issues
title: "[Docs]: "
labels: ["documentation", "triage"]
type: documentation
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation is essential for the ORISO project.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear or confusing content
        - Broken links
        - Code examples need improvement
        - API documentation needs update
        - Setup/installation guide needs update
        - Other
    validations:
      required: true

  - type: dropdown
    id: doc-location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      options:
        - ORISO-Docs (Mintlify platform docs)
        - README.md (repository README)
        - Code comments
        - API documentation
        - Setup guides
        - Architecture documentation
        - GitHub documentation (.github)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue or what documentation is needed
      placeholder: |
        What documentation is missing, incorrect, or needs improvement?
        
        If reporting an issue with existing docs, please include:
        - What is wrong?
        - What should it say instead?
      render: markdown
    validations:
      required: true

  - type: textarea
    id: affected-repo
    attributes:
      label: Affected Repository/File
      description: Which repository or file(s) need documentation updates?
      placeholder: |
        - Repository: [e.g., ORISO-Frontend, ORISO-UserService]
        - File(s): [e.g., README.md, docs/api.md, src/components/UserProfile.tsx]
      render: markdown
    validations:
      required: false

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Content (Optional)
      description: If you have suggestions for the documentation content, please provide it here
      placeholder: |
        If you'd like to suggest specific content, add it here...
      render: markdown
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or links that would help
      placeholder: |
        - Why is this documentation needed?
        - Who would benefit from it?
        - Any related issues or PRs?
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true
        - label: I have checked the documentation location mentioned above
          required: true


