name: Create Labels Across Repositories

on:
  push:
    paths:
      - '.github/workflows/create-labels.yml'
      - '.github/scripts/create-labels.sh'
    branches:
      - main
      - master
  workflow_dispatch:  # Optional: Manual trigger if needed (for re-running)

# ⚠️ IMPORTANT: This workflow only runs when:
# 1. The workflow file itself is pushed/updated
# 2. The create-labels.sh script is updated
# 3. Manual trigger from Actions tab
# It does NOT run on every push to the repository

permissions:
  contents: write  # Needed to create labels in repositories

jobs:
  create-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          type -p curl >/dev/null || (apt update && apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update \
          && apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Make script executable
        run: chmod +x .github/scripts/create-labels.sh

      - name: Create labels across all repositories
        env:
          CI: true  # Set CI flag for non-interactive mode
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash .github/scripts/create-labels.sh

      - name: Summary
        if: always()
        run: |
          echo "## ✅ Label Creation Workflow Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The label creation script has been executed across all ORISO repositories." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**What was done:**" >> $GITHUB_STEP_SUMMARY
          echo "- Created/updated 22 labels in 17 repositories" >> $GITHUB_STEP_SUMMARY
          echo "- Labels include: Work Type, Priority, Area, Size, State, and Special labels" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "1. ✅ Verify labels in any repository: \`Settings → Labels\`" >> $GITHUB_STEP_SUMMARY
          echo "2. ✅ Create a test PR to see auto-labeling in action" >> $GITHUB_STEP_SUMMARY
          echo "3. ✅ Labels are now ready for your PR validation workflow!" >> $GITHUB_STEP_SUMMARY
